# Generated by Django 4.1.5 on 2023-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=7, verbose_name='Phone number'),
        ),
    ]
